# Generated by Django 5.1.7 on 2025-04-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_author_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название для пагинации')),
                ('description', models.CharField(max_length=200, verbose_name='Описание для пагинации')),
            ],
        ),
    ]
